server:
  port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 11T-parad1s3
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user_registration
        username: root
    jpa:
        show-sql: true  
        hibernate:
            ddl-auto: update