spring:
  application:
    name: productsapp
  datasource:
    url: jdbc:mysql://localhost:3306/productsapp
    username: root
    password: 11T-parad1s3
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
#spring:
#    application:
#        name: productsapp
#    datasource:
#        url: jdbc:h2:mem:productsapp
#        username: sa
#        password: password
#        driverClassName: org.h2.Driver
#    jpa:
#        database-platform: org.hibernate.dialect.H2Dialect
#        show-sql: true
#    h2:
#        console.enabled: true